import React from "react";

import {Dialog, Transition} from "@headlessui/react";


interface ModalProps {
  show: boolean;
  onClickClose: () => void;
}

const StartModal = ({show, onClickClose}: ModalProps): JSX.Element => {
  const ref = React.useRef(null);

  return (
    <Transition.Root show={show} as={React.Fragment}>
      <Dialog as="div" ref={ref} initialFocus={ref} className="relative z-10" onClose={onClickClose}>
        <Transition.Child
          as={React.Fragment}
          enter="ease-out duration-300"
          enterFrom="opacity-0"
          enterTo="opacity-100"
          leave="ease-in duration-200"
          leaveFrom="opacity-100"
          leaveTo="opacity-0"
        >
          <div className="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" />
        </Transition.Child>

        <div className="fixed inset-0 z-10 overflow-y-auto">
          <div className="flex min-h-full items-center justify-center p-4 text-center sm:items-center sm:p-0">
            <Transition.Child
              as={React.Fragment}
              enter="ease-out duration-300"
              enterFrom="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
              enterTo="opacity-100 translate-y-0 sm:scale-100"
              leave="ease-in duration-200"
              leaveFrom="opacity-100 translate-y-0 sm:scale-100"
              leaveTo="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
            >
              <Dialog.Panel className="relative transform overflow-hidden rounded-lg bg-white text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg">
                <div className="bg-white px-4 pb-4 pt-5 sm:p-6 sm:pb-4">
                  <div className="sm:flex sm:items-start">
                    <div className="mt-1 text-center sm:ml-4 sm:mt-0 sm:text-left">
                      <Dialog.Title as="h3" className="text-base font-semibold leading-6 text-gray-900">
                        About Game
                      </Dialog.Title>
                      <div className="mt-2">
                        <div className="text-sm text-gray-600">
                          <p>
                            One dead is a strategic guessing game. The goal of the game to correctly guess a four
                            digit number generated by computer with least amount of tries and in the least amount
                            of time
                          </p>

                          <br />

                          <p>
                            For every trial that you make you are given two clues, dead and injured.
                            Dead count is the number of digits that you guessed correctly and are in the correct
                            position. Injured count is the number of digits that you guessed correctly but are in
                            the wrong position.
                          </p>

                          <br />

                          <p>
                            For example, if the number is 1234 and you guessed 1356, you will get 1 dead and 1 injured.
                            Since the dead number would be 1 and the injured number would be 3. The dead digit is 1
                            because 1 is in the correct position. The injured digit is 3 because 3 is in the wrong
                            position.
                          </p>


                          {/*
                          <br />
                            <p>
                              The game also has a hint feature. The hint feature will give you a hint about the number.
                              The hint feature will give you the digit that is in the correct position. For example,
                              if the number is 1234 and you guessed 1356, the hint feature will give you 1 as a hint.
                            <p>
                              If you enjoy the game, please consider donating to the developer. You can donate by
                              clicking the donate button below.
                            </p>

                            <br />

                            <div className="flex justify-center">
                              <a href="https://www.paypal.com/donate?hosted_button_id=ZQZQZQZQZQZQZ" target="_blank" rel="noreferrer">
                                <img src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" alt="Donate" />
                              </a>
                            </div>
                          */}

                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="bg-gray-50 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">
                  <button
                    type="button"
                    className="mt-3 inline-flex w-full justify-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 sm:mt-0 sm:w-auto"
                    onClick={() => onClickClose()}
                  >
                    Start
                  </button>
                </div>
              </Dialog.Panel>
            </Transition.Child>
          </div>
        </div>
      </Dialog>
    </Transition.Root >
  );
};


export default StartModal;
